<?php
declare(strict_types=1);

namespace BetterRestApiLogs\Logger;

defined( 'ABSPATH' ) || exit;

use BetterRestApiLogs\Domain\RequestSnapshot;
use BetterRestApiLogs\Domain\ResponseSnapshot;

/**
 * Per-request UUID-keyed queue holding {request, response} snapshot pairs.
 *
 * Implements the D-05 queue contract and the D-03 outermost-request-id flag
 * for recursion dedupe. Static state lives for exactly one PHP request —
 * PHP-FPM resets class statics at each request boundary, so nothing persists
 * across requests, to DB, cache, or transients (T-03-20 accepted).
 *
 * Tests call reset() in set_up to isolate; production code must never call it —
 * doing so would clear the outermost flag and cause nested rest_do_request calls
 * to be double-logged (D-33 seam restriction).
 */
final class Queue {

	/**
	 * @var array<string,array{request: RequestSnapshot, response: ?ResponseSnapshot}>
	 */
	private static array $queue = [];

	private static ?string $outermost_request_id = null;

	/**
	 * Add a request snapshot to the queue under the given UUID.
	 *
	 * Replaces any prior entry at that UUID; the response side starts null.
	 *
	 * @param string          $uuid Request UUID generated by the Capture orchestrator.
	 * @param RequestSnapshot $req  Pre-dispatch snapshot to store.
	 */
	public static function push( string $uuid, RequestSnapshot $req ): void {
		self::$queue[ $uuid ] = [
			'request'  => $req,
			'response' => null,
		];
	}

	/**
	 * Attach a response snapshot to an existing queue entry.
	 *
	 * Unknown UUIDs are silently ignored — backfill is a no-op per T-03-21
	 * (misattribution guard). The request side is left untouched.
	 *
	 * @param string           $uuid Request UUID to match against the queue.
	 * @param ResponseSnapshot $res  Post-dispatch snapshot to attach.
	 */
	public static function backfill( string $uuid, ResponseSnapshot $res ): void {
		if ( ! isset( self::$queue[ $uuid ] ) ) {
			return;
		}
		self::$queue[ $uuid ]['response'] = $res;
	}

	/**
	 * Return the full queue for draining.
	 *
	 * Callers (Flusher) iterate this and persist each entry. The array is
	 * keyed by UUID.
	 *
	 * @return array<string,array{request: RequestSnapshot, response: ?ResponseSnapshot}>
	 */
	public static function all(): array {
		return self::$queue;
	}

	/**
	 * UUID of the first REST request that entered pre_dispatch this PHP request.
	 *
	 * Null until set_outermost_request_id() is called. The Capture orchestrator
	 * sets this on the very first pre_dispatch and skips nested calls where this
	 * is already non-null (D-03 recursion guard, T-03-19 mitigation).
	 */
	public static function outermost_request_id(): ?string {
		return self::$outermost_request_id;
	}

	/**
	 * Mark a UUID as the outermost request for this PHP request lifecycle.
	 *
	 * Idempotent — subsequent calls overwrite, but the orchestrator only ever
	 * calls this once per outermost pre_dispatch.
	 *
	 * @param string $uuid UUID of the outermost REST request.
	 */
	public static function set_outermost_request_id( string $uuid ): void {
		self::$outermost_request_id = $uuid;
	}

	/**
	 * Reset all static state to initial values.
	 *
	 * @internal Test seam per D-33. Production code MUST NOT call this —
	 *           clearing the outermost flag mid-request would break the D-03
	 *           recursion guard and cause nested rest_do_request calls to be
	 *           logged as separate rows.
	 */
	public static function reset(): void {
		self::$queue                = [];
		self::$outermost_request_id = null;
	}
}
